name: geo-tutorials
channels:
  - conda-forge
  - defaults
  - ncas
  - conda-forge/label/broken
dependencies:
  - pyngl==1.6.1
  - pynio==1.5.5
  - nbserverproxy
  - xarray
  - netcdf4
  - pip
  - cfgrib
  - dask-labextension=1.1.0
  - intake
  - intake-xarray
  - intake-esm
  - fsspec
  - intake-stac
  - cf-python
  - cf-plot=3.0.29
  - udunits2
  - pip:
    - graphviz
    - numpy >= 1.0
    - flake8 >= 2.0
    - line_profiler >= 1.0
    - nose >= 1.3.1
    - cython >= 0.22
    - pox >= 0.2.2
    - dill >= 0.2.5
    - multiprocess >= 0.70.4
    - ppft >= 1.6.4.5
    - pathos >= 0.2.0
    - llvmlite >= 0.2.2
    - numba >= 0.17.0
