name: geo-tutorials
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - pyngl==1.6.1
  - pynio==1.5.5
  - nbserverproxy
  - xarray
  - netcdf4
  - pip
  - cfgrib
  - pip:
    - graphviz
    - dask_labextension
